# -*- coding: utf-8 -*-
"""V3-G4 (user 2026-05-27 拍板): 40_Knowledge_Base 統一管理 — 日常 + 外部 兩大入口.

對齊:
- V3 §5 vault skeleton 40_Knowledge_Base (廢舊 41/42/43/44 細分)
- V3 §13 Memory Router L4 (Knowledge_Base 撈 top-3 進 prompt section F)
- V3 §21 curator 4 層流動: L3 24h 寫 41_Daily / L4 7d 寫 42_External
- MISSION §3.4 RAG + .DB 雙寫 (寫 markdown + 自動 index 到 .ai/sqlite-index.db)
- MISSION §3.6 文獻吸收致用 = 系統核心承諾

新結構:
  40_Knowledge_Base/
  ├── 41_Daily_Knowledge/                 (對話累積, curator L3 24h 寫)
  │   └── <topic>.md
  ├── 42_External_Knowledge/              (外部文獻, curator L4 7d 寫)
  │   ├── _ingest_inbox/                  (user 拖檔 / hermes 抓資料的入口)
  │   │   └── <raw_file>.md
  │   └── <topic>.md                      (LLM 摘要後)
  └── (sqlite-index.db 自動 index, hybrid_search 撈)

兩入口 = 兩種升格管道:
  Daily:    raw_events (chat) → episodic (DB) → 41_Daily/<topic>.md (curator L3)
  External: _ingest_inbox/<file>.md → LLM 摘要 → 42_External/<topic>.md (curator L4)
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from agent_memory.security.atomic import atomic_write


DAILY_DIR = "40_Knowledge_Base/41_Daily_Knowledge"
EXTERNAL_DIR = "40_Knowledge_Base/42_External_Knowledge"
INGEST_INBOX_DIR = "40_Knowledge_Base/42_External_Knowledge/_ingest_inbox"


def _safe_topic_filename(topic: str) -> str:
    """Topic → safe filename. 移除特殊字元 + 截 80 char."""
    safe = re.sub(r'[\\/:"*?<>|]+', '_', topic).strip()
    safe = re.sub(r'\s+', '_', safe)
    return safe[:80] or "untitled"


def write_daily_knowledge(
    vault_root: Path,
    topic: str,
    claim: str,
    *,
    source_event_ids: Optional[list[str]] = None,
    confidence: float = 0.6,
    tags: Optional[list[str]] = None,
) -> Optional[Path]:
    """V3-G4: 寫 41_Daily_Knowledge/<topic>.md.

    curator L3 24h 跑時用: LLM 摘要當日對話 → 提煉 (topic, claim) → 寫此.
    對齊 V3 §11 三層升格中段 (mid level).

    Returns: 寫入路徑 (失敗回 None).
    """
    if not topic or not claim:
        return None
    source_event_ids = source_event_ids or []
    tags = tags or []
    now = datetime.now(timezone.utc).isoformat()
    target = vault_root / DAILY_DIR / f"{_safe_topic_filename(topic)}.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "---",
        "type: daily_knowledge",
        "schema_version: 10",
        f"topic: {topic}",
        f"confidence: {confidence:.4f}",
        f"source_event_count: {len(source_event_ids)}",
        f"tags: {tags}",
        f"created_at: {now}",
        f"updated_at: {now}",
        "lifecycle_state: mid",
        "knowledge_source: daily_conversation",
        "---",
        f"# {topic}",
        "",
        "## 我學到的",
        "",
        claim,
        "",
    ]
    if source_event_ids:
        lines.append("## 來源 raw_events")
        lines.append("")
        for eid in source_event_ids[:10]:
            lines.append(f"- {eid}")
        lines.append("")
    lines.append("---")
    lines.append(f"*Auto-generated by knowledge_base.py V3-G4 ({now[:19]})*")

    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


def write_external_knowledge(
    vault_root: Path,
    topic: str,
    content: str,
    *,
    source_path: Optional[Path] = None,
    summary: Optional[str] = None,
    confidence: float = 0.8,
    tags: Optional[list[str]] = None,
) -> Optional[Path]:
    """V3-G4: 寫 42_External_Knowledge/<topic>.md.

    curator L4 7d 跑時用: 掃 _ingest_inbox/ 新檔 → LLM 摘要 → 寫此.
    對齊 V3 §11 三層升格 + MISSION §3.6 文獻吸收致用.

    Returns: 寫入路徑 (失敗回 None).
    """
    if not topic or not content:
        return None
    tags = tags or []
    now = datetime.now(timezone.utc).isoformat()
    target = vault_root / EXTERNAL_DIR / f"{_safe_topic_filename(topic)}.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "---",
        "type: external_knowledge",
        "schema_version: 10",
        f"topic: {topic}",
        f"confidence: {confidence:.4f}",
        f"source_path: {source_path or '(direct)'}",
        f"tags: {tags}",
        f"created_at: {now}",
        f"updated_at: {now}",
        "lifecycle_state: long",
        "knowledge_source: external_ingest",
        "---",
        f"# {topic}",
        "",
    ]
    if summary:
        lines.append("## 摘要")
        lines.append("")
        lines.append(summary)
        lines.append("")
    lines.append("## 完整內容")
    lines.append("")
    lines.append(content[:5000])  # 截 5000 char 避免 prompt 過載
    lines.append("")
    lines.append("---")
    lines.append(f"*Auto-generated by knowledge_base.py V3-G4 ({now[:19]})*")
    if source_path:
        lines.append(f"*原始檔: {source_path}*")

    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


def list_ingest_inbox(vault_root: Path) -> list[Path]:
    """V3-G4: 列 42_External_Knowledge/_ingest_inbox/ 內待整理 .md / .txt.

    curator L4 7d 跑時用, 對齊 V3-F4 obsidian_watcher 模式.
    """
    inbox = vault_root / INGEST_INBOX_DIR
    if not inbox.exists():
        return []
    files = []
    for ext in (".md", ".txt", ".pdf"):
        files.extend(inbox.glob(f"*{ext}"))
    return sorted(files, key=lambda p: p.stat().st_mtime)


def retrieve_knowledge(
    vault_root: Path,
    query: str,
    *,
    top_k: int = 3,
    max_char_per_hit: int = 200,
) -> list[dict]:
    """V3-G4: hybrid retrieve 40_Knowledge_Base (走 V2 既有 sqlite-index FTS5+vector).

    對齊 V3 §13 Memory Router L4 + MISSION §3.4 RAG 機械化檢索.
    不 call LLM, 純機械 hybrid search.

    Returns: [{path, summary, score, source}, ...]
    """
    if not query.strip():
        return []
    try:
        from agent_memory.search.manager import SearchManager
        from agent_memory.config import load_settings
    except Exception:
        # V2 search infrastructure 沒接, fallback 純 substring match
        return _fallback_substring_search(vault_root, query, top_k, max_char_per_hit)

    try:
        settings = load_settings(vault_root)
        manager = SearchManager(vault_root, settings)
        # 限制只搜 40_Knowledge_Base 內
        results = manager.hybrid_search(query, top_k=top_k * 3)
        knowledge_hits = []
        for r in results:
            path_str = str(getattr(r, "path", ""))
            if "40_Knowledge_Base" not in path_str:
                continue
            summary = (getattr(r, "summary", "") or "")[:max_char_per_hit]
            knowledge_hits.append({
                "path": path_str,
                "summary": summary,
                "score": float(getattr(r, "score", 0.0)),
                "source": "daily" if "41_Daily" in path_str else "external",
            })
            if len(knowledge_hits) >= top_k:
                break
        return knowledge_hits
    except Exception:
        return _fallback_substring_search(vault_root, query, top_k, max_char_per_hit)


def _fallback_substring_search(
    vault_root: Path, query: str, top_k: int, max_char: int,
) -> list[dict]:
    """No-V2-search fallback: 純 substring 全掃 40_Knowledge_Base."""
    base = vault_root / "40_Knowledge_Base"
    if not base.exists():
        return []
    hits = []
    query_lower = query.lower()
    for md in base.rglob("*.md"):
        if md.name.startswith("_") or md.is_dir():
            continue
        try:
            content = md.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if query_lower in content.lower():
            # 抓 query 附近 ±100 char
            idx = content.lower().find(query_lower)
            start = max(0, idx - 50)
            end = min(len(content), idx + 50)
            snippet = content[start:end].replace("\n", " ")
            hits.append({
                "path": str(md.relative_to(vault_root)),
                "summary": snippet[:max_char],
                "score": 0.5,
                "source": "daily" if "41_Daily" in str(md) else "external",
            })
    return sorted(hits, key=lambda h: -h["score"])[:top_k]
