# -*- coding: utf-8 -*-
"""V3-G6 (user 2026-05-27 audit Plan B): 5 區 vault markdown writer 統一.

對齊 V3-F 待做清單 F2/F3/F5/F6/F7 + V3 §5 vault skeleton 雙寫設計.

5 個 writer:
- F2 write_emotion_event_md: 強情緒事件 → 30_Emotional_State/32_Appraisal_Events/<event_id>.md
- F3 write_drift_candidate_md: Drift Guard 候選 → 70_Persona_Versions/73_Candidates/<trait>.md
- F5 write_mood_diary_md: 每日心情 → 30_Emotional_State/34_Mood_Diary/<date>.md
- F5 write_daily_journal_md: 每日總覽 → 90_Daily_Journal/<date>.md
- F6 write_preference_md: 偏好條目 → 60_Preference_Memory/{61_Owner,62_Viewer}/<topic>.md
- F7 write_decision_trace_md: Decision trace → 80_Audit_Trace/81_Decision_Traces/<trace_id>.md
- F7 write_injection_audit_md: 注入攔截 audit → 80_Audit_Trace/83_Injection_Detected/<event>.md

所有 writer atomic_write + frontmatter schema_v10.
不 call LLM (LLM 摘要由 curator L3/L4 處理, 對齊 MISSION §5.4).
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from agent_memory.security.atomic import atomic_write


# Dir constants
EMOTION_EVENT_DIR = "30_Emotional_State/32_Appraisal_Events"
MOOD_DIARY_DIR = "30_Emotional_State/34_Mood_Diary"
DAILY_JOURNAL_DIR = "90_Daily_Journal"
PERSONA_CANDIDATE_DIR = "70_Persona_Versions/73_Candidates"
OWNER_PREF_DIR = "60_Preference_Memory/61_Owner_Preferences"
VIEWER_PREF_DIR = "60_Preference_Memory/62_Viewer_Preferences"
DECISION_TRACE_DIR = "80_Audit_Trace/81_Decision_Traces"
MEMORY_AUDIT_DIR = "80_Audit_Trace/82_Memory_Audit"
INJECTION_AUDIT_DIR = "80_Audit_Trace/83_Injection_Detected"


def _safe_filename(s: str, max_len: int = 80) -> str:
    safe = re.sub(r'[\\/:"*?<>|]+', '_', s).strip()
    safe = re.sub(r'\s+', '_', safe)
    return safe[:max_len] or "untitled"


# ─── F2: 強情緒事件 markdown ─────────────────────────────────────────
def write_emotion_event_md(
    vault_root: Path,
    *,
    event_id: str,
    user_id: str,
    valence: float,
    arousal: float,
    dominance: float,
    user_message: str,
    bot_reply: str,
    dominant_emotion: str = "neutral",
    salience: float = 0.7,
    emotional_salience: float = 0.7,
) -> Optional[Path]:
    """V3-G6 F2: |valence|>0.7 觸發, chat_runtime Step 17 後寫."""
    target = vault_root / EMOTION_EVENT_DIR / f"{event_id[:30]}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "---",
        "type: emotional_memory",
        "schema_version: 10",
        f"event_id: {event_id}",
        f"user_id: {user_id}",
        f"valence: {valence:.4f}",
        f"arousal: {arousal:.4f}",
        f"dominance: {dominance:.4f}",
        f"dominant_emotion: {dominant_emotion}",
        f"salience: {salience:.4f}",
        f"emotional_salience: {emotional_salience:.4f}",
        f"created_at: {now}",
        "lifecycle_state: mid",
        "---",
        f"# 強情緒事件 — {dominant_emotion} (val={valence:+.2f})",
        "",
        "## 觸發訊息",
        "",
        user_message[:500],
        "",
        "## 我的回應",
        "",
        bot_reply[:500],
        "",
        f"*Auto-generated by markdown_writers.py V3-G6 ({now[:19]})*",
    ]
    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


# ─── F3: Drift Guard 候選 markdown ───────────────────────────────────
def write_drift_candidate_md(
    vault_root: Path,
    *,
    trait_name: str,
    proposed_value: float,
    evidence_count: int,
    drift_score: float,
    evidence_event_ids: Optional[list[str]] = None,
) -> Optional[Path]:
    """V3-G6 F3: trait_evolution evidence ≥ 7 + drift_guard 過 → 寫候選."""
    evidence_event_ids = evidence_event_ids or []
    now = datetime.now(timezone.utc).isoformat()
    safe_name = _safe_filename(trait_name)
    target = vault_root / PERSONA_CANDIDATE_DIR / f"{safe_name}_{now[:19].replace(':', '-')}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "---",
        "type: persona_version_candidate",
        "schema_version: 10",
        f"trait_name: {trait_name}",
        f"proposed_value: {proposed_value:.4f}",
        f"evidence_count: {evidence_count}",
        f"drift_score: {drift_score:.4f}",
        "awaiting_active: true",
        "active: false",
        f"created_at: {now}",
        "---",
        f"# Drift Guard 候選 — {trait_name}",
        "",
        f"建議新 value: **{proposed_value:.4f}** (drift={drift_score:.2f}, evidence={evidence_count})",
        "",
        "## Evidence (raw_events)",
        "",
    ]
    for eid in evidence_event_ids[:10]:
        lines.append(f"- {eid}")
    lines.extend([
        "",
        "## user 動作 (對齊 V3 §22 Drift Guard 紅線)",
        "",
        "1. 中之人 review 內容",
        "2. 如同意 → 改 frontmatter `awaiting_active: false` + `active: true`",
        "3. 系統下次重啟 → 此 trait 漂移生效",
        "",
        f"*Auto-generated by markdown_writers.py V3-G6 ({now[:19]})*",
    ])
    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


# ─── F5: Mood Diary + Daily Journal ──────────────────────────────────
def write_mood_diary_md(
    vault_root: Path,
    *,
    date: str,
    avg_valence: float,
    avg_arousal: float,
    dominant_emotions: list[str],
    event_count: int,
    summary: str = "",
) -> Optional[Path]:
    """V3-G6 F5: 每日心情總覽, curator L3 24h 跑時呼叫."""
    target = vault_root / MOOD_DIARY_DIR / f"{date}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "---",
        "type: mood_diary",
        "schema_version: 10",
        f"date: {date}",
        f"avg_valence: {avg_valence:.4f}",
        f"avg_arousal: {avg_arousal:.4f}",
        f"dominant_emotions: {dominant_emotions}",
        f"event_count: {event_count}",
        f"created_at: {now}",
        "---",
        f"# Mood Diary — {date}",
        "",
        f"- 平均心情: valence={avg_valence:+.2f}, arousal={avg_arousal:.2f}",
        f"- 強情緒事件: {event_count} 次",
        f"- 主導情緒: {', '.join(dominant_emotions) if dominant_emotions else 'neutral'}",
        "",
    ]
    if summary:
        lines.extend(["## 今日感受 (LLM 摘要)", "", summary, ""])
    lines.append(f"*Auto-generated by markdown_writers.py V3-G6 ({now[:19]})*")
    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


def write_daily_journal_md(
    vault_root: Path,
    *,
    date: str,
    total_interactions: int,
    owner_interactions: int,
    viewer_interactions: int,
    knowledge_added: int,
    summary: str = "",
) -> Optional[Path]:
    """V3-G6 F5: 每日總覽, curator L3 24h 跑時呼叫."""
    target = vault_root / DAILY_JOURNAL_DIR / f"{date}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "---",
        "type: daily_journal",
        "schema_version: 10",
        f"date: {date}",
        f"total_interactions: {total_interactions}",
        f"owner_interactions: {owner_interactions}",
        f"viewer_interactions: {viewer_interactions}",
        f"knowledge_added: {knowledge_added}",
        f"created_at: {now}",
        "---",
        f"# Daily Journal — {date}",
        "",
        f"- 總互動: {total_interactions}",
        f"- 跟主人: {owner_interactions}",
        f"- 跟觀眾: {viewer_interactions}",
        f"- 學到知識: {knowledge_added}",
        "",
    ]
    if summary:
        lines.extend(["## 今天的我", "", summary, ""])
    lines.append(f"*Auto-generated by markdown_writers.py V3-G6 ({now[:19]})*")
    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


# ─── F6: Preference markdown ─────────────────────────────────────────
def write_preference_md(
    vault_root: Path,
    *,
    topic: str,
    claim: str,
    user_id: str,
    is_owner: bool,
    strength: float,
    confidence: float,
    evidence_count: int,
    status: str = "active",
) -> Optional[Path]:
    """V3-G6 F6: preference_consolidator 升 episodic+ 時呼叫."""
    safe_topic = _safe_filename(topic)
    target_dir = OWNER_PREF_DIR if is_owner else VIEWER_PREF_DIR
    target = vault_root / target_dir / f"{user_id[:30]}_{safe_topic}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "---",
        "type: preference",
        "schema_version: 10",
        f"user_id: {user_id}",
        f"topic: {topic}",
        f"strength: {strength:.4f}",
        f"confidence: {confidence:.4f}",
        f"evidence_count: {evidence_count}",
        f"status: {status}",
        f"is_owner: {is_owner}",
        f"created_at: {now}",
        f"updated_at: {now}",
        "---",
        f"# {'主人' if is_owner else '觀眾'}偏好 — {topic}",
        "",
        f"## 我學到的",
        "",
        claim[:300],
        "",
        f"## 元資料",
        "",
        f"- strength: {strength:.2f}",
        f"- confidence: {confidence:.2f}",
        f"- evidence_count: {evidence_count}",
        f"- status: {status}",
        "",
        f"*Auto-generated by markdown_writers.py V3-G6 ({now[:19]})*",
    ]
    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


# ─── F7: Decision Trace + Memory Audit + Injection Audit ─────────────
def write_decision_trace_md(
    vault_root: Path,
    *,
    trace_id: str,
    user_id: str,
    decision: str,
    factor_scores: dict,
    hard_rules_triggered: list[str],
    policy: dict,
    user_message: str,
    bot_reply: str,
) -> Optional[Path]:
    """V3-G6 F7: chat_runtime Step 19 trace_logs 寫時同步寫 markdown."""
    target = vault_root / DECISION_TRACE_DIR / f"{trace_id[:30]}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "---",
        "type: decision_trace",
        "schema_version: 10",
        f"trace_id: {trace_id}",
        f"user_id: {user_id}",
        f"decision: {decision}",
        f"created_at: {now}",
        "---",
        f"# Decision Trace — {decision}",
        "",
        f"## User message",
        "",
        user_message[:200],
        "",
        f"## Bot reply",
        "",
        bot_reply[:200],
        "",
        f"## 8 因子分數",
        "",
    ]
    for k, v in factor_scores.items():
        lines.append(f"- {k}: {v:.4f}")
    lines.extend([
        "",
        f"## Hard Rules 觸發",
        "",
    ])
    if hard_rules_triggered:
        for h in hard_rules_triggered:
            lines.append(f"- {h}")
    else:
        lines.append("- (無)")
    lines.extend([
        "",
        f"## Policy",
        "",
        f"- strategy: {policy.get('strategy')}",
        f"- tone: {policy.get('tone')}",
        f"- intimacy_score: {policy.get('intimacy_score')}",
        "",
        f"*Auto-generated by markdown_writers.py V3-G6 ({now[:19]})*",
    ])
    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


def write_injection_audit_md(
    vault_root: Path,
    *,
    detected_id: str,
    user_id: str,
    pattern_matched: str,
    risk_score: float,
    user_message: str,
    action_taken: str = "scanner_flagged",
) -> Optional[Path]:
    """V3-G6 F7: chat_runtime Step 17 寫 injection_detected DB 時同步寫 markdown."""
    target = vault_root / INJECTION_AUDIT_DIR / f"{detected_id[:30]}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat()
    lines = [
        "---",
        "type: injection_audit",
        "schema_version: 10",
        f"detected_id: {detected_id}",
        f"user_id: {user_id}",
        f"risk_score: {risk_score:.4f}",
        f"action_taken: {action_taken}",
        f"created_at: {now}",
        "---",
        f"# Injection Detected",
        "",
        f"## Pattern Matched",
        "",
        pattern_matched[:300],
        "",
        f"## User Message (原文)",
        "",
        user_message[:500],
        "",
        f"## Action",
        "",
        f"- {action_taken}",
        f"- risk_score: {risk_score:.4f}",
        "",
        f"*Auto-generated by markdown_writers.py V3-G6 ({now[:19]})*",
    ]
    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None
