# -*- coding: utf-8 -*-
"""V3-K3 (user 2026-05-27 「自我成長小孩」核心):
narrative_memories — 夥伴的「自我敘事弧」.

對齊 V3 §24 Narrative Memory + user 「哲學資料庫」設計理念.

設計:
- curator L4 7d deep 跑時, 對每個有充足互動的 user 寫一筆 narrative
- 撈該 user 過去 7d 的 intim 變化 + emotion trajectory + 強情緒事件
- LLM 寫 narrative arc: 「我跟 user X 從 ... 到 ... 的成長故事」
- 寫 narrative_memories DB + vault md
- Memory Router L3 撈 narrative 進 prompt

vault md: 30_Emotional_State/36_Narratives/<user_id>_<period>.md (新區)
"""
from __future__ import annotations

import json
import re
import uuid
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from agent_memory.companion.companion_db import open_companion_db
from agent_memory.security.atomic import atomic_write


NARRATIVE_DIR = "30_Emotional_State/36_Narratives"  # V3-K3 新區


def _safe_filename(s: str, max_len: int = 60) -> str:
    safe = re.sub(r'[\\/:"*?<>|]+', '_', s).strip()
    safe = re.sub(r'\s+', '_', safe)
    return safe[:max_len] or "untitled"


def write_narrative_memory(
    vault_root: Path,
    *,
    user_id: str,
    theme: str,
    events_chain: list[str],
    relationship_arc: str,
    emotional_arc: dict,  # {start_valence, peak_valence, end_valence, ...}
    narrative_text: str = "",
) -> Optional[Path]:
    """V3-K3: 寫 narrative_memories DB + vault markdown."""
    if not user_id or not theme:
        return None
    narrative_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    # 寫 DB
    try:
        with open_companion_db(vault_root) as conn:
            conn.execute(
                "INSERT INTO narrative_memories (narrative_id, user_id, theme, events_chain_json, "
                "relationship_arc, emotional_arc_json, created_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (narrative_id, user_id, theme,
                 json.dumps(events_chain, ensure_ascii=False),
                 relationship_arc,
                 json.dumps(emotional_arc, ensure_ascii=False),
                 now),
            )
            conn.commit()
    except Exception:
        return None

    # 寫 vault markdown
    period_label = now[:10]  # YYYY-MM-DD
    safe_uid = _safe_filename(user_id)[:30]
    target = vault_root / NARRATIVE_DIR / f"{safe_uid}_{period_label}_{narrative_id[:8]}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "---",
        "type: narrative_memory",
        "schema_version: 10",
        f"narrative_id: {narrative_id}",
        f'user_id: "{user_id}"',
        f"theme: {theme}",
        f"relationship_arc: {relationship_arc}",
        f"events_count: {len(events_chain)}",
        f"start_valence: {emotional_arc.get('start_valence', 0.0):.2f}",
        f"peak_valence: {emotional_arc.get('peak_valence', 0.0):.2f}",
        f"end_valence: {emotional_arc.get('end_valence', 0.0):.2f}",
        f"period: {period_label}",
        f"created_at: {now}",
        "knowledge_source: narrative_consolidation",
        "---",
        f"# 我跟 {user_id[:16]} 的敘事弧 — {theme}",
        "",
        "## 關係演化",
        "",
        relationship_arc,
        "",
    ]
    if narrative_text:
        lines.append("## 完整敘事 (LLM 整理)")
        lines.append("")
        lines.append(narrative_text)
        lines.append("")
    if events_chain:
        lines.append("## 主要事件鏈")
        lines.append("")
        # ⭐ V3-N (user 2026-05-27): 加 [[wikilinks]] 連回 episodic MD
        for eid in events_chain[:10]:
            lines.append(f"- [[{eid}]]")
        lines.append("")
    lines.append(f"## 情緒弧 (Emotional Arc)")
    lines.append("")
    lines.append(f"- 起始 valence: {emotional_arc.get('start_valence', 0.0):+.2f}")
    lines.append(f"- 峰值 valence: {emotional_arc.get('peak_valence', 0.0):+.2f}")
    lines.append(f"- 結束 valence: {emotional_arc.get('end_valence', 0.0):+.2f}")
    lines.append("")
    lines.append("---")
    lines.append(f"*Auto-generated by narrative_writer.py V3-K3 ({now[:19]})*")

    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


def list_recent_narratives(
    vault_root: Path, user_id: str, max_count: int = 2,
) -> list[dict]:
    """V3-K3: 撈該 user 最近 narrative 給 Memory Router L3 用."""
    if not user_id:
        return []
    try:
        with open_companion_db(vault_root) as conn:
            rows = conn.execute(
                "SELECT theme, relationship_arc, emotional_arc_json, created_at "
                "FROM narrative_memories WHERE user_id=? "
                "ORDER BY created_at DESC LIMIT ?",
                (user_id, max_count),
            ).fetchall()
    except Exception:
        return []
    result = []
    for r in rows:
        try:
            arc = json.loads(r["emotional_arc_json"] or "{}")
        except Exception:
            arc = {}
        result.append({
            "theme": r["theme"] or "",
            "relationship_arc": r["relationship_arc"] or "",
            "emotional_arc": arc,
            "created_at": r["created_at"] or "",
        })
    return result


def build_narrative_arc_via_llm(vault_root: Path) -> int:
    """V3-K3: curator L4 7d 跑時, 對每個活躍 user 寫一筆 narrative.

    對齊 V3 §24 + V3 §11 三層升格 long-term + user 「哲學資料庫」.

    Returns: 寫入的 narrative 數.
    """
    try:
        from agent_memory.llm_client import LLMClient
        from agent_memory.llm_text_helpers import call_llm_for_text
    except Exception:
        return 0

    cutoff_7d = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()
    try:
        with open_companion_db(vault_root) as conn:
            # 撈過去 7d 有充足互動 (>= 5 turn) 的 user
            users = conn.execute(
                "SELECT user_id, COUNT(*) AS c FROM raw_events "
                "WHERE created_at > ? AND actor='user' GROUP BY user_id HAVING c >= 5",
                (cutoff_7d,),
            ).fetchall()
    except Exception:
        return 0

    if not users:
        return 0

    try:
        client = LLMClient(vault_root)
    except Exception:
        return 0

    written = 0
    for u in users[:3]:  # 限每跑 3 user 避免 LLM 爆量
        user_id = u["user_id"]
        if not user_id or user_id == "anonymous":
            continue

        # 撈該 user 過去 7d 強情緒事件 + intim 變化
        try:
            with open_companion_db(vault_root) as conn:
                events = conn.execute(
                    "SELECT memory_id, summary, valence, created_at FROM episodic_memories "
                    "WHERE user_id=? AND created_at > ? AND ABS(valence) > 0.4 "
                    "ORDER BY created_at ASC LIMIT 10",
                    (user_id, cutoff_7d),
                ).fetchall()
                # intim 起始 vs 現在
                intim_now = conn.execute(
                    "SELECT intimacy_score FROM intimacy_states WHERE user_id=?",
                    (user_id,),
                ).fetchone()
                # 第一次 emotion (proxy for start)
                first_emo = conn.execute(
                    "SELECT joy, sadness, dominant_emotion, timestamp FROM emotion_state "
                    "WHERE user_id=? AND timestamp > ? ORDER BY timestamp ASC LIMIT 1",
                    (user_id, cutoff_7d),
                ).fetchone()
                # 最近 emotion
                last_emo = conn.execute(
                    "SELECT joy, sadness, dominant_emotion, timestamp FROM emotion_state "
                    "WHERE user_id=? ORDER BY timestamp DESC LIMIT 1",
                    (user_id,),
                ).fetchone()
        except Exception:
            continue

        if not events or len(events) < 2:
            continue

        # 算 emotional arc
        start_valence = float(events[0]["valence"] or 0.0)
        end_valence = float(events[-1]["valence"] or 0.0)
        peak_valence = max((float(e["valence"] or 0.0) for e in events), key=abs)

        # 餵 LLM 寫敘事
        events_text = "\n".join(
            f"- [{(e['created_at'] or '')[:10]}] valence={e['valence']:.2f}, {(e['summary'] or '')[:100]}"
            for e in events
        )
        intim_score = float(intim_now["intimacy_score"]) if intim_now else 0.0
        prompt = (
            "你是夥伴大腦的 sleep cycle curator (long-term narrative consolidation).\n"
            "以下是夥伴跟 user 過去 7 天的強情緒事件鏈, 請整理成一段「我跟他的敘事弧」(narrative arc).\n\n"
            "請輸出 4 段 (每段一行, 格式如下):\n"
            "THEME: <一句話總結這段關係主題, ≤30 字>\n"
            "RELATIONSHIP_ARC: <一句話描述關係演化, e.g. 「從陌生到熟識的好奇試探」≤50 字>\n"
            "NARRATIVE: <一段敘事 ≤200 字, 用第一人稱「我」, 對齊「自我成長的孩子」口吻>\n"
            "(每段都用「我」開頭, 表達夥伴自我視角)\n\n"
            f"User: {user_id[:16]}\n"
            f"intimacy: {intim_score:.2f}\n"
            f"事件鏈:\n{events_text}\n\n"
            "輸出 (僅 3 行, 無解釋):"
        )
        try:
            result = call_llm_for_text(client, prompt, persona_id="companion", max_tokens=500, auxiliary="narrative_synthesis")
            text = (result.text or "").strip()
        except Exception:
            continue

        # Parse
        theme = ""
        rel_arc = ""
        narrative = ""
        for line in text.split("\n"):
            line = line.strip()
            if line.startswith("THEME:"):
                theme = line.split(":", 1)[1].strip()[:60]
            elif line.startswith("RELATIONSHIP_ARC:"):
                rel_arc = line.split(":", 1)[1].strip()[:100]
            elif line.startswith("NARRATIVE:"):
                narrative = line.split(":", 1)[1].strip()[:500]
        if not theme or not rel_arc:
            continue

        path = write_narrative_memory(
            vault_root,
            user_id=user_id,
            theme=theme,
            events_chain=[e["memory_id"] for e in events],
            relationship_arc=rel_arc,
            emotional_arc={
                "start_valence": start_valence,
                "peak_valence": peak_valence,
                "end_valence": end_valence,
            },
            narrative_text=narrative,
        )
        if path:
            written += 1
    return written
