# -*- coding: utf-8 -*-
"""V3-K2 (user 2026-05-27 「自我成長小孩」核心):
semantic_memories 自我提煉概念 + 寫 vault markdown.

對齊:
- V3 §11 三層升格 (raw_events → episodic → semantic)
- V3 §10.2 Preference Lifecycle (但 semantic_memories 是更廣義的「夥伴自己學到的概念」)
- user 「自然記憶」 = 從事件中**提煉概念**, 不只記事件

設計:
- curator L3 24h 加 _consolidate_semantic_concepts:
  - 撈近 24h |valence|>0.3 + emotional_salience>0.5 episodic_memories
  - 同 user_id 重複出現 ≥ 2 次的 topic → 寫 semantic claim
  - LLM 提煉「我發現 X 對 Y 有效」格式
  - 寫 semantic_memories DB
  - 同步寫 vault markdown 給 LLM 看
- chat_runtime Memory Router L3 加 semantic_memories 撈

寫 vault: 30_Emotional_State/35_Self_Concepts/<claim_id>.md (新區)
"""
from __future__ import annotations

import json
import re
import uuid
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from agent_memory.companion.companion_db import open_companion_db
from agent_memory.security.atomic import atomic_write


SELF_CONCEPTS_DIR = "30_Emotional_State/35_Self_Concepts"  # V3-K2 新區


def _safe_filename(s: str, max_len: int = 60) -> str:
    safe = re.sub(r'[\\/:"*?<>|]+', '_', s).strip()
    safe = re.sub(r'\s+', '_', safe)
    return safe[:max_len] or "untitled"


def write_semantic_concept(
    vault_root: Path,
    *,
    user_id: str,
    claim: str,
    derived_from: list[str],  # episodic memory_ids
    confidence: float = 0.6,
    tags: Optional[list[str]] = None,
    topic_label: str = "",
) -> Optional[Path]:
    """V3-K2: 寫 semantic_memories DB + 寫 vault markdown.

    Returns: vault markdown 路徑 (DB 寫成功但 markdown 失敗也 OK, 仍 return None).
    """
    if not user_id or not claim:
        return None
    tags = tags or []
    memory_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    # 寫 DB
    try:
        with open_companion_db(vault_root) as conn:
            conn.execute(
                "INSERT INTO semantic_memories (memory_id, user_id, claim, derived_from, "
                "confidence, evidence_count, contradiction_count, tags, status, created_at) "
                "VALUES (?, ?, ?, ?, ?, ?, 0, ?, 'semantic', ?)",
                (memory_id, user_id, claim,
                 json.dumps(derived_from, ensure_ascii=False),
                 confidence, len(derived_from),
                 json.dumps(tags, ensure_ascii=False),
                 now),
            )
            conn.commit()
    except Exception:
        return None

    # 寫 vault markdown
    topic_hint = topic_label or claim[:30]
    target = vault_root / SELF_CONCEPTS_DIR / f"{_safe_filename(topic_hint)}_{memory_id[:8]}.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "---",
        "type: self_concept",
        "schema_version: 10",
        f"memory_id: {memory_id}",
        f"user_id: {user_id}",
        f"confidence: {confidence:.4f}",
        f"evidence_count: {len(derived_from)}",
        f"tags: {tags}",
        f"status: semantic",
        f"created_at: {now}",
        "knowledge_source: self_reflection",
        "---",
        f"# 我學到的概念 — {topic_hint}",
        "",
        "## Claim (我發現)",
        "",
        claim,
        "",
    ]
    if derived_from:
        lines.append("## Evidence (episodic memories)")
        lines.append("")
        # ⭐ V3-N (user 2026-05-27 拍板): 加 [[wikilinks]] 連回 episodic MD
        # Obsidian Graph view 看 self_concept → event 關連; backlinks panel 反查
        for eid in derived_from[:10]:
            lines.append(f"- [[{eid}]]")
        lines.append("")
    lines.append("---")
    lines.append(f"*Auto-generated by semantic_writer.py V3-K2 ({now[:19]})*")

    try:
        atomic_write(target, "\n".join(lines) + "\n")
        return target
    except Exception:
        return None


def list_recent_semantic_concepts(
    vault_root: Path, user_id: Optional[str] = None,
    *, max_count: int = 5,
) -> list[dict]:
    """V3-K2: 撈該 user (或全部) 最近 semantic 概念給 Memory Router L3 用.

    Returns: [{claim, confidence, evidence_count, tags, created_at}, ...]
    """
    try:
        with open_companion_db(vault_root) as conn:
            if user_id:
                rows = conn.execute(
                    "SELECT claim, confidence, evidence_count, tags, created_at FROM semantic_memories "
                    "WHERE user_id=? AND status='semantic' "
                    "ORDER BY confidence DESC, evidence_count DESC LIMIT ?",
                    (user_id, max_count),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT claim, confidence, evidence_count, tags, created_at FROM semantic_memories "
                    "WHERE status='semantic' ORDER BY confidence DESC LIMIT ?",
                    (max_count,),
                ).fetchall()
    except Exception:
        return []
    result = []
    for r in rows:
        result.append({
            "claim": r["claim"] or "",
            "confidence": float(r["confidence"] or 0.0),
            "evidence_count": int(r["evidence_count"] or 0),
            "tags": r["tags"] or "[]",
            "created_at": r["created_at"] or "",
        })
    return result


def consolidate_semantic_concepts_via_llm(vault_root: Path) -> int:
    """V3-K2: curator L3 用 LLM 從近 24h episodic 提煉 semantic 概念.

    對齊 V3 §11.2 升格 + V2 R9 LLM consolidation.
    純機械 prompt: 「找重複觀察 → 提煉「我發現 X 對 Y 有效」」.

    Returns: 寫入的 concept 數.
    """
    try:
        from agent_memory.llm_client import LLMClient
        from agent_memory.llm_text_helpers import call_llm_for_text
    except Exception:
        return 0

    cutoff_24h = (datetime.now(timezone.utc) - timedelta(hours=24)).isoformat()
    try:
        with open_companion_db(vault_root) as conn:
            # 撈近 24h 中等以上情緒的 episodic
            rows = conn.execute(
                "SELECT user_id, summary, valence, arousal, emotional_salience, memory_id "
                "FROM episodic_memories "
                "WHERE created_at > ? AND ABS(valence) > 0.3 AND emotional_salience > 0.4 "
                "AND lifecycle_state IN ('short','mid') "
                "ORDER BY emotional_salience DESC LIMIT 8",
                (cutoff_24h,),
            ).fetchall()
    except Exception:
        return 0

    if len(rows) < 2:
        return 0  # 少於 2 個 episodic 沒辦法提煉概念

    try:
        client = LLMClient(vault_root)
    except Exception:
        return 0

    # 用 LLM 從這批 episodic 提煉 1-3 個 semantic claim
    episodes_text = "\n".join(
        f"- [{r['memory_id'][:8]}] user_id={r['user_id'][:12]}, "
        f"valence={r['valence']:.2f}, summary={(r['summary'] or '')[:120]}"
        for r in rows
    )
    prompt = (
        "你是夥伴大腦的 sleep cycle curator. 以下是近 24h 中等以上情緒的對話事件 (episodic).\n"
        "請從這些事件中提煉 1-3 個「夥伴自己學到的概念」(semantic memory).\n"
        "格式: 每條一行, 「TOPIC|CLAIM|EVIDENCE_IDS(逗號分隔, 從上面 memory_id 抓)」\n"
        "例: 「主人偏好直接|我發現主人喜歡不繞圈廢話的回應, 過去 3 次都有效|abc123,def456」\n"
        "Claim 用第一人稱「我發現 / 我學到」開頭, ≤80 字.\n\n"
        f"事件:\n{episodes_text}\n\n"
        f"輸出 (僅 1-3 行, 無解釋):"
    )
    try:
        result = call_llm_for_text(client, prompt, persona_id="companion", max_tokens=500)
        text = (result.text or "").strip()
    except Exception:
        return 0

    # Parse LLM 輸出
    written = 0
    for line in text.split("\n"):
        line = line.strip()
        if not line or "|" not in line:
            continue
        parts = line.split("|", 2)
        if len(parts) != 3:
            continue
        topic = parts[0].strip()[:60]
        claim = parts[1].strip()[:200]
        evidence_ids_str = parts[2].strip()
        evidence_ids = [e.strip() for e in evidence_ids_str.split(",") if e.strip()][:5]
        if not topic or not claim:
            continue

        # 用第一個 episodic 的 user_id 當代表 (簡化)
        first_uid = rows[0]["user_id"] if rows else ""

        path = write_semantic_concept(
            vault_root,
            user_id=first_uid,
            claim=claim,
            derived_from=evidence_ids,
            confidence=0.7,
            tags=["sleep_cycle", "self_concept"],
            topic_label=topic,
        )
        if path:
            written += 1
    return written
